import {
	faPencilAlt,
	faCode,
	faUsers,
	faCogs,
} from "@fortawesome/free-solid-svg-icons";

const jobList = [
	{
		title: "Senior PHP Developer",
		priority: true,
		location: "Remote | Spokane - Austin - SLC - ",
		workType: "Full Time",
		salary: "$160,000/year",
		icon: faCode,
		note: "",
		route: "/software/senior-php-developer",
	},
	{
		title: "Senior Software Engineer (Ruby on Rails)",
		priority: true,
		location: "Remote | Spokane - Austin - SLC - ",
		workType: "Full Time",
		salary: "$185,000/year",
		icon: faCode,
		note: "",
		route: "/software/senior-engineer",
	},
	{
		title: "Information Security Director",
		priority: true,
		location: "Remote | Spokane - Austin - SLC - ",
		workType: "Full Time",
		salary: "$200,000/year",
		icon: faUsers,
		note: "",
		route: "/information-security-director",
	},
	{
		title: "VOIP Business Manager",
		priority: true,
		location: "Remote | Spokane - Austin - SLC - ",
		workType: "Full Time",
		salary: "$200,000/year",
		icon: faCode,
		note: "",
		route: "/management/director-of-voip",
	},
	{
		title: "Product Manager",
		priority: true,
		location: "Remote | Spokane - Austin - SLC - ",
		workType: "Full Time",
		salary: "$65,000 - $120,000/year DOE",
		icon: faCode,
		note: "Sorry for the range, but we have so many products and we're open to paying people from all experience ranges to help run our products.",
		route: "/software/product-manager",
	},
	{
		title: "Senior Software Engineer - VoIP",
		priority: false,
		location: "Spokane, WA | Austin, TX | Sale Lake, UT - ",
		workType: "Remote - Full Time",
		salary: "$185,000/year",
		icon: faCode,
		note: "",
		route: "/software/senior-software-engineer-voip",
	},
	{
		title: "Senior Backend Developer",
		priority: false,
		location: "Remote | Spokane - Austin - SLC - ",
		workType: "Full Time",
		salary: "$185,000/year",
		icon: faCode,
		note: "",
		route: "/software/senior-backend-developer",
	},
	{
		title: "Senior Data Engineer",
		priority: false,
		location: "Remote | Spokane - Austin - SLC - ",
		workType: "Full Time",
		salary: "$150,000/year",
		icon: faCode,
		note: "",
		route: "/software/senior-data-engineer",
	},
	{
		title: "Security Engineer",
		priority: false,
		location: "Remote | Spokane - Austin - SLC - ",
		workType: "Full Time",
		salary: "$175,000/year",
		icon: faCogs,
		note: "",
		route: "/systems/security-engineer",
	},
	{
		title: "Senior Front-End Web Developer",
		priority: false,
		location: "Remote | Spokane - Austin - SLC - ",
		workType: "Full Time",
		salary: "$150,000/year",
		icon: faPencilAlt,
		note: "",
		route: "/websites/senior-front-web-developer",
	},
	{
		title: "Senior DevOps Engineer",
		priority: false,
		location: "Remote | Spokane - Austin - SLC - ",
		workType: "Full Time",
		salary: "$140,000 - $170,000/year",
		icon: faCode,
		note: "",
		route: "/software/devops-engineers",
	},
	{
		title: "Director of Software Engineering",
		priority: false,
		location: "Spokane WA, Austin TX, Salt Lake UT vicinity preferred - ",
		workType: "Full Time",
		salary: "$200,000/year",
		icon: faUsers,
		note: "We are family owned and run, so there's no share compensation or bonus structure as part of the compensation package.",
		route: "/software/director-of-software-engineering",
	},
	{
		title: "Chief Marketing Officer",
		priority: false,
		location: "Spokane - Austin - Salt Lake City - ",
		workType: "Full Time",
		salary: "Up to $350,000/year DOE",
		icon: faUsers,
		note: "It's a family owned and operated business, and as such, it's just a normal type salary compensation package. Relocation assistance available for Spokane only. Depending on your network and ability to attract talent localy, we are also considering candidates who already live near our Austin TX or Salt Lake City UT offices, but we cannot offer relocation assistance to these cities.",
		route: "/websites/chief-marketing-officer",
	},
	{
		title: "Junior Graphic Designer",
		priority: false,
		location: "Spokane, WA - ",
		workType: "Full Time",
		salary: "$55,000 - $60,000/year",
		icon: faPencilAlt,
		note: "(Candidates qualify for the higher end of the range if you have a degree in Design.)",
		route: "/websites/junior-graphic-designer",
	},
];

export default jobList;
