export const jobDetails = {
	"senior-php-developer": {
		title: "Senior PHP Developer",
		overview:
			"<p>Two Barrels is hiring Senior Software Engineers specializing in PHP/Laravel for $160,000/year. You will be a traditional company employee. This is a full time 40 hour/week position with company benefits. This is a remote position. Our main office is in Spokane WA, and we have satellite offices in Austin TX and Salt Lake City UT.<br>You will be given large projects and be expected to break these projects into medium-sized tasks for our Software Engineers, all while maintaining focus on the big picture goals and projects. You will have the opportunity to make a direct impact on architecture design. You’ll get to work with a team of engineers who like to do things the right way versus plowing through just to meet a goal. We have no investors or micro-managed goals. We just want to make high-end software that is easy to continually improve. You can expect a diverse team with different backgrounds, experience and identities. You will have current members of the team eager to help you get up to speed as quickly as possible. Solid fundamentals with software, teamwork, systems, and troubleshooting will pave the way. </p><p><strong>What’s in a title? </strong><br>Here at Two Barrels we don’t take titles very seriously. We know for recruiting purposes we need to call our jobs something, so we started with labeling and differentiating them in a fairly traditional way with “junior, mid, senior”. However, we’ve realized that was putting our employees in a box and wasn’t allowing us to uniquely identify their individual contributions, strengths and professional goals. Once you join our team the titles kinda get dropped as we expect everyone to work with everyone regardless of title or experience. We have taken the approach of evaluating candidates and employees on a “level” basis. It makes it a little easier internally to talk about growing into the next level without there being this huge chasm between what it means to be a Junior Engineer vs. a Mid Engineer. Our levels have expectations set for each one and it’s the responsibility of the manager and employee to make sure there is alignment. We do this through quarterly conversations where we discuss employee progression, if the work is challenging, and to ensure they feel fairly compensated for their work and expertise. Basically, levels give us more flexibility to help people grow in their careers. But sure, you can post your title on LinkedIn as what makes sense to the rest of the world. </p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$160,000/year",
		responsibilities: [
			"Be a good human",
			"Treat your co-workers with respect",
			"Have a Growth Mindset, not a Fixed Mindset",
			"Be ready to learn, expect there to be a decent amount of 'figure things out'",
			"Be willing to research and explore the domain space",
			"Become the expert in our PHP code and maintain/improve it; integrate it with our existing systems",
			"Help us set a high bar for quality, from code and systems to how we treat each other",
			"Monitor and ensure automated processes run as expected",
			"Perform routine automation assignments with minimum supervision",
			"Communicate consistently with stakeholders, managers, and other teams about releases",
			"Participate in the training or development of others, as directed",
		],
		minimumQualifications: [
			"Bachelor’s degree in computer science or other equivalent degree/experience",
			"Minimum of 6 years full stack application development, software test automation experience, and object oriented development",
			"4+ years working with back-end frameworks like Laravel",
			"4+ years working front-end frameworks such as Vue, Angular, React, etc.",
			"2+ years working with relational databases and writing SQL queries or stored procedures",
			"Experience mentoring junior to mid-level engineers while balancing current work",
			"Proficient in vanilla JavaScript (outside of using it with a modern web framework)",
		],
		preferredQualifications: [
			"Experience working in the domain space",
			"Experirence working with MySql",
		],
		youMightLikeThisJob:
			"<p>You want to make cool stuff. You want your cool stuff to be really good.  But most importantly, if you made a dish of noodles and butter for someone and asked them what they thought of it, if they said it was okay or good and didn’t give you feedback, you’d feel a little left out… you’d want a little more… because okay or good isn’t fulfilling to you.</p>",
	},
	"senior-engineer": {
		title: "Senior Software Engineer (Ruby on Rails)",
		overview:
			"<p>Two Barrels is hiring Senior Software Engineers specializing in Ruby on Rails for $185,000/year. You will be a traditional company employee. This is a full time 40 hour/week position with company benefits. This is a remote position. Our main office is in Spokane WA, and we have satellite offices in Austin TX and Salt Lake City UT.</p><p>As a Senior Software Engineer, you will be given large projects and be expected to break these projects into medium-sized tasks for our Software Engineers, all while maintaining focus on the big picture goals and projects. You will have the opportunity to make a direct impact on architecture design. You’ll get to work with a team of engineers who like to do things the right way versus plowing through just to meet a goal. We have no investors or micro-managed goals. We just want to make high-end software that is easy to continually improve.</p><p>You can expect a diverse team with different backgrounds, experience and identities. You will have current members of the team eager to help you get up to speed as quickly as possible. Solid fundamentals with software, teamwork, systems, and troubleshooting will pave the way.</p><p><strong>What’s in a title?</strong></p><p>Here at Two Barrels we don’t take titles very seriously. We know for recruiting purposes we need to call our jobs something, so we started with labeling and differentiating them in a fairly traditional way with “junior, mid, senior”. However, we’ve realized that was putting our employees in a box and wasn’t allowing us to uniquely identify their individual contributions, strengths and professional goals. Once you join our team the titles kinda get dropped as we expect everyone to work with everyone regardless of title or experience. We have taken the approach of evaluating candidates and employees on a “level” basis. It makes it a little easier internally to talk about growing into the next level without there being this huge chasm between what it means to be a Junior Engineer vs. a Mid Engineer. Our levels have expectations set for each one and it’s the responsibility of the manager and employee to make sure there is alignment. We do this through quarterly conversations where we discuss employee progression, if the work is challenging, and to ensure they feel fairly compensated for their work and expertise. Basically, levels gives us more flexibility to help people grow in their careers. But sure, you can post your title on LinkedIn as what makes sense to the rest of the world.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$185,000/year",
		responsibilities: [
			"Be a good human",
			"Treat your co-workers with respect",
			"Have a Growth Mindset, not a Fixed Mindset",
			"Remember that it's a marathon, not a sprint. Help us bring calm to what can creep into a rush",
			"Design, implement, document, and maintain front and back end systems for high-traffic applications",
			"Help peel off monolith code into well-organized architecture",
			"Help drive technical standards for the team",
			"Design and implement novel systems from scratch, from billing to all kinds of crazy ideas we come up with",
			"Help us set a high bar for quality, from code and systems to how we treat each other",
			"Take substantial features from concept to shipping",
			"Provide material feedback on the work of junior and mid-level programmers",
			"Monitor and ensure automated processes run as expected",
			"Perform routine automation assignments with minimum supervision",
			"Communicate consistently with stakeholders, managers, and other teams about releases",
			"Participate in the training or development of others, as directed",
			"Be willing to learn, grow, and help all of us continually get better at what we do",
		],
		minimumQualifications: [
			"Bachelor’s degree in computer science or other equivalent degree/experience",
			"Minimum of 6 years full stack application development, software test automation experience, and object oriented development",
			"4+ years working with back-end frameworks like Rails, Laravel, Django, etc.",
			"4+ years working front-end frameworks such as Vue, Angular, React, etc.",
			"2+ years working with relational databases and writing SQL queries or stored procedures",
			"Advanced level of querying in ORMs such as ActiveRecord and Sequel",
			"Experience mentoring junior to mid-level engineers while balancing current work",
			"High proficiency in some of the following AWS services: ECS, EC2, S3, CloudWatch, RDS, ElasticSearch, VPC",
			"Proficient in vanilla JavaScript (outside of using it with a modern web framework)",
		],
		preferredQualifications: [
			"High level of ability coding in Ruby and expert level familiarity with the Rails framework",
			"Experience with large Rails/Rack- based applications",
		],
		youMightLikeThisJob:
			"<p>You’ve been building large rails apps for other companies. The ones with carrots dangling in front of you, hipster benefits and slippery ladders. You’ve always wondered if there’s a place where profits and titles aren’t everyone’s motivation. Where people just want you to make great software. You like the idea of working for a locally-owned and operated company that competes in an extremely competitive space nationwide. You like that your work matters today and will affect millions of our business customers.</p><p>You like the idea that you could find a place like this in Spokane, where we have 4 seasons. Where you can buy a great house for a great price with no epic commute. You like that there are 5 ski hills within 2 hours and endless outdoor activities. You don’t like bugs or humidity or a million people living in your city.</p><p>You love to code, but you want to take part in the planning without being required to deal with stakeholders and project managers all day. You want to make cool stuff. You want your cool stuff to be really good.&nbsp; But most importantly, if you made a dish of noodles and butter for someone and asked them what they thought of it, if they said it was okay or good and didn’t give you feedback, you’d feel a little left out… you’d want a little more… because okay or good isn’t fulfilling to you.</p><p>But at the same time… it’s just a job. Yourself/Family/Friends/Personal Time is number 1. Work is number 2 or 3. Our goal is to use the incredible business we are excited to be a part of to support all of our personal time. We all want to live a full personal life. We’ll have more fun working together during the day if we know there’s a clear cutoff. This way, we can create a work environment where we can not only go home at the end of the day, but mentally shut off work and mentally go home also. We focus on creating a welcoming, supportive job environment that pays well and doesn’t stress you out, so when you call it a day, you go have fun personally.</p><p><b>#BI-Remote</b></p>",
	},
	"information-security-director": {
		title: "Information Security Director",
		overview:
			"<p align='left'>Two Barrels is hiring an Information Security Director to build, lead and develop our Security team. You will be a traditional company employee. This is a full-time 40 hours/week position with company benefits.</p><p align='left'>As a 'Director,' you will be responsible for overseeing security as well as actually doing the work of a security engineer as we grow this team. Ultimately, if you are solely looking for the prestige of being a 'Director,' this probably isn’t the right place for you. We are not looking for a figurehead to fill this seat; we want someone who is going to get their hands dirty and do the work. But because your title will be 'Information Security Director,' you will need to be able to push and grow the team. You have been there and done that in the security world, help some people out!</p><p align='left'>You like being hands-on and doing the actual work, but you also like the tactical part of this and looking at things from a higher level. You are a professional and don’t laugh at job titles like 'Penetration Tester' even though it’s funny. More importantly, you know what someone in that role is doing, and you can do some of it yourself if not all of it. Your role is technical, but you’re also a leader, so you’re a technical leader. We have Operations Managers who aren’t technical, so we need you to be technical… so you’re a technical leader of technical people who do technical things.</p><p align='left'>This is a remote or work-wherever-you-want position. Of course, we’d prefer you be around Spokane, Salt Lake, or Austin to have a hub based out of one of our three main offices, but we’re open to good talent anywhere in the US.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$200,000/year",
		responsibilities: [
			"Solve problems, don't just bring them to our attention",
			"Find open source solutions, we like to build things, not buy things",
			"Create cutting-edge processes that will leverage automation to improve our resiliency and position ourselves better to respond to security events",
			"Develop and implement a comprehensive security strategy that aligns with our business objectives and priorities",
			"Drive education initiatives company-wide to create security-minded employees",
			"Lead security initiatives and ensure compliance with applicable regulatory requirements, such as HIPAA, PCI, and GDPR",
			"Stay up to date on the newest security technologies and methodologies",
			"Provide development and feedback to team members",
			"Responsible for team growth",
		],
		minimumQualifications: [
			"Be a good human",
			"Have a build versus buy mentality",
			"5+ years of experience in Computer Science or a related field required with at least 2 of those years in Cyber Security",
			"2+ years in a technical leadership role ",
			"Experience with building, managing and developing a team",
			"Experience with Linux and the ability to secure Linux-based systems",
			"Working knowledge of the Ruby on Rails framework, including its security features and vulnerabilities",
			"Able to identify the problem, not just the symptoms",
			"Ability to take a holistic approach to security, identifying vulnerabilities and risks across the entire system, including areas that individual teams or departments may overlook or not be aware of ",
			"Comfortable working in an ambiguous environment",
			"Solid understanding of AWS infrastructure, including security features, compliance requirements, and best practices for securing cloud environments",
			"Basic understanding of Kubernetes architecture, its security features, and how to secure Kubernetes clusters",
			"Open source solutions are your go to",
		],
		preferredQualifications: [
			"Experience in leading security incident response efforts",
			"You have grown a security group from the ground up",
			"You're a nice person",
			"You thrive on the chaos of a place that is always coming out with great ideas",
		],
		youMightLikeThisJob:
			"<p align='left'>You think like a hacker and know what they’re going to do, but you are one of the good guys and want to use your security powers for good, not evil. You recognize real security risks and pride yourself on identifying the problem and not just the symptoms of the problem. You want to educate people, including developers and customer service reps, about how to avoid security problems.</p><p align='left'>We’re family owned and provide a secure platform for our clients to do good work, and we want to keep it that way. Privacy, security, and ease of mind for our people; let’s keep that going. We have a lot of good people here who want to see that continue, and you want to push it farther down that road.</p><p align='left'><b>#BI-Remote</b></p>",
	},
	"director-of-voip": {
		title: "VOIP Business Manager",
		overview:
			"<p>We’re trying to build the most private phone service on planet earth.</p><p>Our objective is to create an amazing user experience via through both browsers and apps. The phone service must also be as private as technically possible, as reliable as possible, and resilient as possible, for as cheap as possible. It should go without saying, we’re looking for someone who enjoys a challenge.</p><p>We service over 3 million active businesses nationwide and there’s a huge opportunity here to make our phone service awesome. We run on Verizon’s backbone, combined with AWS and Kamailio with native Android and iOS. This is an active service line for us, but it currently is not what we envisioned. We’ve had great ideas but horrible execution. We seek a visionary that is really into phones and VOIP. You’ll own the product from customer service all the way to through the actual tech running it. Phones and VOIP should be a passion for you. And I don’t mean managing a Cisco switch or some dumb corporate crap like that.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$200,000/year",
		responsibilities: [
			"Make and run the most private phone service legally possible in the US.",
			"Run this like a business, make it a profitable product",
			"Manage team growth by need and p&l",
		],
		minimumQualifications: [
			"You should really really really understand VOIP and scalable services. ",
			"You should be able to explain thoroughly how phone and messages works on all technical levels.",
			"5+ years of experience in Computer Science or a related field required with at least 2 of those years in Cyber Security",
			"2+ years in a technical leadership role ",
			"Experience with building, managing and developing a team",
			"Experience with Linux and the ability to secure Linux-based systems",
			"Working knowledge of the Ruby on Rails framework, including its security features and vulnerabilities",
			"Able to identify the problem, not just the symptoms",
			"Ability to take a holistic approach to security, identifying vulnerabilities and risks across the entire system, including areas that individual teams or departments may overlook or not be aware of ",
			"Comfortable working in an ambiguous environment",
			"Solid understanding of AWS infrastructure, including security features, compliance requirements, and best practices for securing cloud environments",
			"Basic understanding of Kubernetes architecture, its security features, and how to secure Kubernetes clusters",
			"Open source solutions are your go to",
		],
		preferredQualifications: [
			"You're kind of a wacko and you've been looking for a wacky place to really do the crazy stuff you've always wanted to do.",
		],
		youMightLikeThisJob:
			"<p>It bugs you to no end that an Apple or Google update defaults all your privacy settings back to not being private. You wish Purism actually had a good phone you could buy and that Linux OS phones were mainstream. We trademarked “Privacy By Default®.” It’s not an advertising thing for us, it’s a true passion. Very likely, you have been involved in the telecom industry for a long time and you can see where the data leaks out the side door, but you’ve never had an employer that cared to keep the user’s information private.</p><p>Once our phone service is good, we’ll be the largest VOIP provider in the country that isn’t Zoom, Teams, Google, or any of the others. We don’t want to compete with them or be in that level of space. We just want to sell a great, reliable private phone app for nine bucks a month to the masses with no upsells. We want it to be amazing! Can you help us get there?</p><p><strong><b>#BI-Remote</b>&nbsp;</strong></p>",
	},
	"product-manager": {
		title: "Product Manager",
		overview:
			"<p>Two Barrels is hiring a Product Manager to join our PM team. You will be a traditional company employee. This is a full time 40 hour M-F position with company benefits. We have offices in Spokane, WA; Austin, TX; and Salt Lake, UT.</p><p>Two Barrels is organized via products. We run a little over 50 products and our products are only as good as an inspired product group. As a Product Manager, you will work with our Product Designers, Stakeholders, and a full stack of skill sets to own our products, run our products, and establish your own product vision, benchmarks, standards, KPIs, and goals for your products.</p><p>Hint: We are looking for you to include in your resume or cover letter some data points on accomplishments you’ve made with products you’ve worked on in the past. Looking for what progress was made on products you lead as a product manager.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$65,000-$120,000/year DOE Sorry for the range, but we have so many products and we're open to paying people from all experience ranges to help run our products.",
		responsibilities: [
			"Define the product, learn what has already been developed",
			"Create strategy for where we want to take the product and how to stay competitive",
			"Define what the development team needs to build by collecting needs and requirements from the operations teams",
			"Communicate across all 2Barrels and operations teams to lead projects and gain traction",
			"Lead cross functional product teams. Manage timelines, expectations, setbacks, and delivery",
			"Gather feedback from clients and employees/stakeholders to continuously improve products and the processes",
			"Collaborate and communicate with company stakeholders, present product progress and setbacks",
			"Conduct competitive analysis",
			"Sift your way through all this nonsense and just get stuff done how you see fit for your product",
		],
		minimumQualifications: [
			"2+ years of demonstrated experience working as a Product Manager in a development environment",
			"Ability to analyze and define business requirements and translate them into functional specifications for developers",
			"Strong analytical and problem-solving skills",
			"Excellent organizational, interpersonal and customer centric approaches",
			"Good communicator with active listening skills, comfortable communicating in high stress environments",
			"Demonstrated fluency in tools like Excel, JIRA, and Confluence",
			"Experience working with cross functional teams and leading projects to delivery",
		],
		preferredQualifications: [
			"Bachelors's degree in product management, engineering, computer Science or other equivalent degree/certificate. ",
			"Experience creating a product roadmap and connecting the needs of all inside and outside stakeholders",
			"Experience with market analyses, pricing and product business justification. ",
			"Experience with product development and all stages of the product life cycle, from introduction to decline.",
			"Can evaluate the market as defined for the product and own the business strategy behind a product.",
			"Resource allocation skills.",
			"Be able to communicate with various types of stakeholders (business vs. technical language).",
		],
		youMightLikeThisJob:
			"<p>You are fascinated with a good experience you had at a business. What went behind that? You are interested in what the user needs, why they need it, and how you build a full product that makes the customer, customer service employees, and the technology employees making that happen behind the scenes function as well as possible. You love the challenge of refining for continual improvement. You think products are actually what makes the world turn.</p><p>#BI-Remote</p>",
	},
	"senior-software-engineer": {
		title: "Senior Software Engineer - VoIP",
		overview:
			"<p>Two Barrels is hiring a Senior Software Engineer – VoIP to join our team for $185,000/year. You will be a traditional company employee. This is a full time 40 hour M-F position with company benefits. This is a remote position. Our main office is in Spokane WA, and we have satellite offices in Austin TX and Salt Lake City UT.</p><p>We are looking for you; a software engineer with strong networking, software and telecom background. VoIP – Voice over Internet Protocol, we are looking for a Senior Software Engineer that has hands on experience building these services, specifically someone who wants to breate a secure network. We’re looking to continue building out our VOIP products and need someone who nerds out on this stuff. To be successful in this role, you should have hands-on experience in configuration, integration and development with VOIP Soft PBX Solution vendors or similar. You’ll work closely with our Telecom PM to make this product bigger and better.</p>",
		location: "Spokane, WA | Austin, TX | Salt Lake, UT | Remote",
		duration: "Full Time",
		wage: "$185,000/year",
		responsibilities: [
			"Be the technical go to for development and enhancement of our phone services",
			"Develop a scalable nationwide VoIP service",
			"Work with Telecom PM to deploy, implement, and support new products and features",
			"Create documentation outlining the design and support of voice products",
			"Continually evolve fraud protection and implement features to support new telecom regulations",
			"Propose and implement performance optimizations",
		],
		minimumQualifications: [
			"BS/BA in Computer Science, Network Engineering or equivalent experience with telecommunications services.",
			"Strong background in developing and deploying VoIP systems (SIP)",
			"Experience in real-time software",
			"Programming experience in Python and/or Ruby, Javascript",
			"At least 3 years experience of service provider deployment and integration",
			"Ability to work independently with support from other teams",
			"Ability to mentor other engineers and teams working within your product",
			"Experience with open source SIP and network systems",
			"Ability to make an impact quickly",
			"Experience working with Asterisk",
			"Be a good human",
		],
		preferredQualifications: [
			"4+ years of Ruby on Rails experience",
			"Experience developing in Kamailio",
			"Ability to adapt to change and continuously improve",
		],
		youMightLikeThisJob:
			"<p>You are tired of paying so much for phone services. You are tired of not having a secure network. You want to help create one of the most secure VoIP networks out there, and make it affordable. In short, you want to solve problems that individuals and business owners care about by providing a good service at an affordable price. Your mission, should you choose to accept it, is not to impress stock holders and the fat cats out there, but to do good work and see it take off like a rocket ship. Is that something you want?</p>",
	},
};

export const benefits = [
	{
		text: "Great Wage",
		route: "/jobs/benefits/wages",
	},
	{
		text: "WFH comfort package",
		route: "/jobs/benefits/wfh-comfort-package",
	},
	{
		text: "22 days paid time off (29 days after 3 years. Flexible time off after 5 years!)",
		route: "/jobs/benefits/pto",
	},
	{
		text: "4% retirement matching through Fidelity",
		route: "/jobs/benefits/retirement",
	},
	{
		text: "100% employer-paid medical, dental and vision for employees",
		route: "/jobs/benefits/health-insurance",
	},
	{
		text: "Maternity and Paternity Leave",
		route: "/jobs/benefits/maternity-paternity-leave",
	},
	{
		text: "Flexible hours",
		route: "/jobs/benefits/flexible-hours",
	},
	{
		text: "Coffee shop next door",
		route: "/jobs/benefits/coffee",
	},
	{
		text: "<del>Crappy parking?</del> Oh, I mean a cool downtown location for easy public transportation options…",
		route: null,
	},
];
