export const jobDetails = {
	"senior-php-developer": {
		title: "Senior PHP Developer",
		overview:
			"<p>Two Barrels is hiring Senior Software Engineers specializing in PHP/Laravel for $160,000/year. You will be a traditional company employee. This is a full time 40 hour/week position with company benefits. This is a remote position. Our main office is in Spokane WA, and we have satellite offices in Austin TX and Salt Lake City UT.<br>You will be given large projects and be expected to break these projects into medium-sized tasks for our Software Engineers, all while maintaining focus on the big picture goals and projects. You will have the opportunity to make a direct impact on architecture design. You’ll get to work with a team of engineers who like to do things the right way versus plowing through just to meet a goal. We have no investors or micro-managed goals. We just want to make high-end software that is easy to continually improve. You can expect a diverse team with different backgrounds, experience and identities. You will have current members of the team eager to help you get up to speed as quickly as possible. Solid fundamentals with software, teamwork, systems, and troubleshooting will pave the way. </p><p><strong>What’s in a title? </strong><br>Here at Two Barrels we don’t take titles very seriously. We know for recruiting purposes we need to call our jobs something, so we started with labeling and differentiating them in a fairly traditional way with “junior, mid, senior”. However, we’ve realized that was putting our employees in a box and wasn’t allowing us to uniquely identify their individual contributions, strengths and professional goals. Once you join our team the titles kinda get dropped as we expect everyone to work with everyone regardless of title or experience. We have taken the approach of evaluating candidates and employees on a “level” basis. It makes it a little easier internally to talk about growing into the next level without there being this huge chasm between what it means to be a Junior Engineer vs. a Mid Engineer. Our levels have expectations set for each one and it’s the responsibility of the manager and employee to make sure there is alignment. We do this through quarterly conversations where we discuss employee progression, if the work is challenging, and to ensure they feel fairly compensated for their work and expertise. Basically, levels give us more flexibility to help people grow in their careers. But sure, you can post your title on LinkedIn as what makes sense to the rest of the world. </p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$160,000/year",
		responsibilities: [
			"Be a good human",
			"Treat your co-workers with respect",
			"Have a Growth Mindset, not a Fixed Mindset",
			"Be ready to learn, expect there to be a decent amount of 'figure things out'",
			"Be willing to research and explore the domain space",
			"Become the expert in our PHP code and maintain/improve it; integrate it with our existing systems",
			"Help us set a high bar for quality, from code and systems to how we treat each other",
			"Monitor and ensure automated processes run as expected",
			"Perform routine automation assignments with minimum supervision",
			"Communicate consistently with stakeholders, managers, and other teams about releases",
			"Participate in the training or development of others, as directed",
		],
		minimumQualifications: [
			"Bachelor’s degree in computer science or other equivalent degree/experience",
			"Minimum of 6 years full stack application development, software test automation experience, and object oriented development",
			"4+ years working with back-end frameworks like Laravel",
			"4+ years working front-end frameworks such as Vue, Angular, React, etc.",
			"2+ years working with relational databases and writing SQL queries or stored procedures",
			"Experience mentoring junior to mid-level engineers while balancing current work",
			"Proficient in vanilla JavaScript (outside of using it with a modern web framework)",
		],
		preferredQualifications: [
			"Experience working in the domain space",
			"Experience working with MySql",
		],
		youMightLikeThisJob:
			"<p>You want to make cool stuff. You want your cool stuff to be really good.  But most importantly, if you made a dish of noodles and butter for someone and asked them what they thought of it, if they said it was okay or good and didn’t give you feedback, you’d feel a little left out… you’d want a little more… because okay or good isn’t fulfilling to you.</p>",
	},
	"senior-engineer": {
		title: "Senior Software Engineer (Ruby on Rails)",
		overview:
			"<p>Two Barrels is hiring Senior Software Engineers specializing in Ruby on Rails for $185,000/year. You will be a traditional company employee. This is a full time 40 hour/week position with company benefits. This is a remote position. Our main office is in Spokane WA, and we have satellite offices in Austin TX and Salt Lake City UT.</p><p>As a Senior Software Engineer, you will be given large projects and be expected to break these projects into medium-sized tasks for our Software Engineers, all while maintaining focus on the big picture goals and projects. You will have the opportunity to make a direct impact on architecture design. You’ll get to work with a team of engineers who like to do things the right way versus plowing through just to meet a goal. We have no investors or micro-managed goals. We just want to make high-end software that is easy to continually improve.</p><p>You can expect a diverse team with different backgrounds, experience and identities. You will have current members of the team eager to help you get up to speed as quickly as possible. Solid fundamentals with software, teamwork, systems, and troubleshooting will pave the way.</p><p><strong>What’s in a title?</strong></p><p>Here at Two Barrels we don’t take titles very seriously. We know for recruiting purposes we need to call our jobs something, so we started with labeling and differentiating them in a fairly traditional way with “junior, mid, senior”. However, we’ve realized that was putting our employees in a box and wasn’t allowing us to uniquely identify their individual contributions, strengths and professional goals. Once you join our team the titles kinda get dropped as we expect everyone to work with everyone regardless of title or experience. We have taken the approach of evaluating candidates and employees on a “level” basis. It makes it a little easier internally to talk about growing into the next level without there being this huge chasm between what it means to be a Junior Engineer vs. a Mid Engineer. Our levels have expectations set for each one and it’s the responsibility of the manager and employee to make sure there is alignment. We do this through quarterly conversations where we discuss employee progression, if the work is challenging, and to ensure they feel fairly compensated for their work and expertise. Basically, levels gives us more flexibility to help people grow in their careers. But sure, you can post your title on LinkedIn as what makes sense to the rest of the world.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$185,000/year",
		responsibilities: [
			"Be a good human",
			"Treat your co-workers with respect",
			"Have a Growth Mindset, not a Fixed Mindset",
			"Remember that it's a marathon, not a sprint. Help us bring calm to what can creep into a rush",
			"Design, implement, document, and maintain front and back end systems for high-traffic applications",
			"Help peel off monolith code into well-organized architecture",
			"Help drive technical standards for the team",
			"Design and implement novel systems from scratch, from billing to all kinds of crazy ideas we come up with",
			"Help us set a high bar for quality, from code and systems to how we treat each other",
			"Take substantial features from concept to shipping",
			"Provide material feedback on the work of junior and mid-level programmers",
			"Monitor and ensure automated processes run as expected",
			"Perform routine automation assignments with minimum supervision",
			"Communicate consistently with stakeholders, managers, and other teams about releases",
			"Participate in the training or development of others, as directed",
			"Be willing to learn, grow, and help all of us continually get better at what we do",
		],
		minimumQualifications: [
			"Bachelor’s degree in computer science or other equivalent degree/experience",
			"Minimum of 6 years full stack application development, software test automation experience, and object oriented development",
			"4+ years working with back-end frameworks like Rails, Laravel, Django, etc.",
			"4+ years working front-end frameworks such as Vue, Angular, React, etc.",
			"2+ years working with relational databases and writing SQL queries or stored procedures",
			"Advanced level of querying in ORMs such as ActiveRecord and Sequel",
			"Experience mentoring junior to mid-level engineers while balancing current work",
			"High proficiency in some of the following AWS services: ECS, EC2, S3, CloudWatch, RDS, ElasticSearch, VPC",
			"Proficient in vanilla JavaScript (outside of using it with a modern web framework)",
		],
		preferredQualifications: [
			"High level of ability coding in Ruby and expert level familiarity with the Rails framework",
			"Experience with large Rails/Rack- based applications",
		],
		youMightLikeThisJob:
			"<p>You’ve been building large rails apps for other companies. The ones with carrots dangling in front of you, hipster benefits and slippery ladders. You’ve always wondered if there’s a place where profits and titles aren’t everyone’s motivation. Where people just want you to make great software. You like the idea of working for a locally-owned and operated company that competes in an extremely competitive space nationwide. You like that your work matters today and will affect millions of our business customers.</p><p>You like the idea that you could find a place like this in Spokane, where we have 4 seasons. Where you can buy a great house for a great price with no epic commute. You like that there are 5 ski hills within 2 hours and endless outdoor activities. You don’t like bugs or humidity or a million people living in your city.</p><p>You love to code, but you want to take part in the planning without being required to deal with stakeholders and project managers all day. You want to make cool stuff. You want your cool stuff to be really good.&nbsp; But most importantly, if you made a dish of noodles and butter for someone and asked them what they thought of it, if they said it was okay or good and didn’t give you feedback, you’d feel a little left out… you’d want a little more… because okay or good isn’t fulfilling to you.</p><p>But at the same time… it’s just a job. Yourself/Family/Friends/Personal Time is number 1. Work is number 2 or 3. Our goal is to use the incredible business we are excited to be a part of to support all of our personal time. We all want to live a full personal life. We’ll have more fun working together during the day if we know there’s a clear cutoff. This way, we can create a work environment where we can not only go home at the end of the day, but mentally shut off work and mentally go home also. We focus on creating a welcoming, supportive job environment that pays well and doesn’t stress you out, so when you call it a day, you go have fun personally.</p><p><b>#BI-Remote</b></p>",
	},
	"information-security-director": {
		title: "Information Security Director",
		overview:
			"<p align='left'>Two Barrels is hiring an Information Security Director to build, lead and develop our Security team. You will be a traditional company employee. This is a full-time 40 hours/week position with company benefits.</p><p align='left'>As a 'Director,' you will be responsible for overseeing security as well as actually doing the work of a security engineer as we grow this team. Ultimately, if you are solely looking for the prestige of being a 'Director,' this probably isn’t the right place for you. We are not looking for a figurehead to fill this seat; we want someone who is going to get their hands dirty and do the work. But because your title will be 'Information Security Director,' you will need to be able to push and grow the team. You have been there and done that in the security world, help some people out!</p><p align='left'>You like being hands-on and doing the actual work, but you also like the tactical part of this and looking at things from a higher level. You are a professional and don’t laugh at job titles like 'Penetration Tester' even though it’s funny. More importantly, you know what someone in that role is doing, and you can do some of it yourself if not all of it. Your role is technical, but you’re also a leader, so you’re a technical leader. We have Operations Managers who aren’t technical, so we need you to be technical… so you’re a technical leader of technical people who do technical things.</p><p align='left'>This is a remote or work-wherever-you-want position. Of course, we’d prefer you be around Spokane, Salt Lake, or Austin to have a hub based out of one of our three main offices, but we’re open to good talent anywhere in the US.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$200,000/year",
		responsibilities: [
			"Solve problems, don't just bring them to our attention",
			"Find open source solutions, we like to build things, not buy things",
			"Create cutting-edge processes that will leverage automation to improve our resiliency and position ourselves better to respond to security events",
			"Develop and implement a comprehensive security strategy that aligns with our business objectives and priorities",
			"Drive education initiatives company-wide to create security-minded employees",
			"Lead security initiatives and ensure compliance with applicable regulatory requirements, such as HIPAA, PCI, and GDPR",
			"Stay up to date on the newest security technologies and methodologies",
			"Provide development and feedback to team members",
			"Responsible for team growth",
		],
		minimumQualifications: [
			"Be a good human",
			"Have a build versus buy mentality",
			"5+ years of experience in Computer Science or a related field required with at least 2 of those years in Cyber Security",
			"2+ years in a technical leadership role ",
			"Experience with building, managing and developing a team",
			"Experience with Linux and the ability to secure Linux-based systems",
			"Working knowledge of the Ruby on Rails framework, including its security features and vulnerabilities",
			"Able to identify the problem, not just the symptoms",
			"Ability to take a holistic approach to security, identifying vulnerabilities and risks across the entire system, including areas that individual teams or departments may overlook or not be aware of ",
			"Comfortable working in an ambiguous environment",
			"Solid understanding of AWS infrastructure, including security features, compliance requirements, and best practices for securing cloud environments",
			"Basic understanding of Kubernetes architecture, its security features, and how to secure Kubernetes clusters",
			"Open source solutions are your go to",
		],
		preferredQualifications: [
			"Experience in leading security incident response efforts",
			"You have grown a security group from the ground up",
			"You're a nice person",
			"You thrive on the chaos of a place that is always coming out with great ideas",
		],
		youMightLikeThisJob:
			"<p align='left'>You think like a hacker and know what they’re going to do, but you are one of the good guys and want to use your security powers for good, not evil. You recognize real security risks and pride yourself on identifying the problem and not just the symptoms of the problem. You want to educate people, including developers and customer service reps, about how to avoid security problems.</p><p align='left'>We’re family owned and provide a secure platform for our clients to do good work, and we want to keep it that way. Privacy, security, and ease of mind for our people; let’s keep that going. We have a lot of good people here who want to see that continue, and you want to push it farther down that road.</p><p align='left'><b>#BI-Remote</b></p>",
	},
	"director-of-voip": {
		title: "VOIP Business Manager",
		overview:
			"<p>We’re trying to build the most private phone service on planet earth.</p><p>Our objective is to create an amazing user experience via through both browsers and apps. The phone service must also be as private as technically possible, as reliable as possible, and resilient as possible, for as cheap as possible. It should go without saying, we’re looking for someone who enjoys a challenge.</p><p>We service over 3 million active businesses nationwide and there’s a huge opportunity here to make our phone service awesome. We run on Verizon’s backbone, combined with AWS and Kamailio with native Android and iOS. This is an active service line for us, but it currently is not what we envisioned. We’ve had great ideas but horrible execution. We seek a visionary that is really into phones and VOIP. You’ll own the product from customer service all the way to through the actual tech running it. Phones and VOIP should be a passion for you. And I don’t mean managing a Cisco switch or some dumb corporate crap like that.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$200,000/year",
		responsibilities: [
			"Make and run the most private phone service legally possible in the US.",
			"Run this like a business, make it a profitable product",
			"Manage team growth by need and p&l",
		],
		minimumQualifications: [
			"You should really really really understand VOIP and scalable services. ",
			"You should be able to explain thoroughly how phone and messages works on all technical levels.",
			"5+ years of experience in Computer Science or a related field required with at least 2 of those years in Cyber Security",
			"2+ years in a technical leadership role ",
			"Experience with building, managing and developing a team",
			"Experience with Linux and the ability to secure Linux-based systems",
			"Working knowledge of the Ruby on Rails framework, including its security features and vulnerabilities",
			"Able to identify the problem, not just the symptoms",
			"Ability to take a holistic approach to security, identifying vulnerabilities and risks across the entire system, including areas that individual teams or departments may overlook or not be aware of ",
			"Comfortable working in an ambiguous environment",
			"Solid understanding of AWS infrastructure, including security features, compliance requirements, and best practices for securing cloud environments",
			"Basic understanding of Kubernetes architecture, its security features, and how to secure Kubernetes clusters",
			"Open source solutions are your go to",
		],
		preferredQualifications: [
			"You're kind of a wacko and you've been looking for a wacky place to really do the crazy stuff you've always wanted to do.",
		],
		youMightLikeThisJob:
			"<p>It bugs you to no end that an Apple or Google update defaults all your privacy settings back to not being private. You wish Purism actually had a good phone you could buy and that Linux OS phones were mainstream. We trademarked “Privacy By Default®.” It’s not an advertising thing for us, it’s a true passion. Very likely, you have been involved in the telecom industry for a long time and you can see where the data leaks out the side door, but you’ve never had an employer that cared to keep the user’s information private.</p><p>Once our phone service is good, we’ll be the largest VOIP provider in the country that isn’t Zoom, Teams, Google, or any of the others. We don’t want to compete with them or be in that level of space. We just want to sell a great, reliable private phone app for nine bucks a month to the masses with no upsells. We want it to be amazing! Can you help us get there?</p><p><strong><b>#BI-Remote</b>&nbsp;</strong></p>",
	},
	"product-manager": {
		title: "Product Manager",
		overview:
			"<p>Two Barrels is hiring a Product Manager to join our PM team. You will be a traditional company employee. This is a full time 40 hour M-F position with company benefits. We have offices in Spokane, WA; Austin, TX; and Salt Lake, UT.</p><p>Two Barrels is organized via products. We run a little over 50 products and our products are only as good as an inspired product group. As a Product Manager, you will work with our Product Designers, Stakeholders, and a full stack of skill sets to own our products, run our products, and establish your own product vision, benchmarks, standards, KPIs, and goals for your products.</p><p>Hint: We are looking for you to include in your resume or cover letter some data points on accomplishments you’ve made with products you’ve worked on in the past. Looking for what progress was made on products you lead as a product manager.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$65,000-$120,000/year DOE Sorry for the range, but we have so many products and we're open to paying people from all experience ranges to help run our products.",
		responsibilities: [
			"Define the product, learn what has already been developed",
			"Create strategy for where we want to take the product and how to stay competitive",
			"Define what the development team needs to build by collecting needs and requirements from the operations teams",
			"Communicate across all 2Barrels and operations teams to lead projects and gain traction",
			"Lead cross functional product teams. Manage timelines, expectations, setbacks, and delivery",
			"Gather feedback from clients and employees/stakeholders to continuously improve products and the processes",
			"Collaborate and communicate with company stakeholders, present product progress and setbacks",
			"Conduct competitive analysis",
			"Sift your way through all this nonsense and just get stuff done how you see fit for your product",
		],
		minimumQualifications: [
			"2+ years of demonstrated experience working as a Product Manager in a development environment",
			"Ability to analyze and define business requirements and translate them into functional specifications for developers",
			"Strong analytical and problem-solving skills",
			"Excellent organizational, interpersonal and customer centric approaches",
			"Good communicator with active listening skills, comfortable communicating in high stress environments",
			"Demonstrated fluency in tools like Excel, JIRA, and Confluence",
			"Experience working with cross functional teams and leading projects to delivery",
		],
		preferredQualifications: [
			"Bachelors's degree in product management, engineering, computer Science or other equivalent degree/certificate. ",
			"Experience creating a product roadmap and connecting the needs of all inside and outside stakeholders",
			"Experience with market analyses, pricing and product business justification. ",
			"Experience with product development and all stages of the product life cycle, from introduction to decline.",
			"Can evaluate the market as defined for the product and own the business strategy behind a product.",
			"Resource allocation skills.",
			"Be able to communicate with various types of stakeholders (business vs. technical language).",
		],
		youMightLikeThisJob:
			"<p>You are fascinated with a good experience you had at a business. What went behind that? You are interested in what the user needs, why they need it, and how you build a full product that makes the customer, customer service employees, and the technology employees making that happen behind the scenes function as well as possible. You love the challenge of refining for continual improvement. You think products are actually what makes the world turn.</p><p>#BI-Remote</p>",
	},
	"senior-software-engineer": {
		title: "Senior Software Engineer - VoIP",
		overview:
			"<p>Two Barrels is hiring a Senior Software Engineer – VoIP to join our team for $185,000/year. You will be a traditional company employee. This is a full time 40 hour M-F position with company benefits. This is a remote position. Our main office is in Spokane WA, and we have satellite offices in Austin TX and Salt Lake City UT.</p><p>We are looking for you; a software engineer with strong networking, software and telecom background. VoIP – Voice over Internet Protocol, we are looking for a Senior Software Engineer that has hands on experience building these services, specifically someone who wants to breate a secure network. We’re looking to continue building out our VOIP products and need someone who nerds out on this stuff. To be successful in this role, you should have hands-on experience in configuration, integration and development with VOIP Soft PBX Solution vendors or similar. You’ll work closely with our Telecom PM to make this product bigger and better.</p>",
		location: "Spokane, WA | Austin, TX | Salt Lake, UT | Remote",
		duration: "Full Time",
		wage: "$185,000/year",
		responsibilities: [
			"Be the technical go to for development and enhancement of our phone services",
			"Develop a scalable nationwide VoIP service",
			"Work with Telecom PM to deploy, implement, and support new products and features",
			"Create documentation outlining the design and support of voice products",
			"Continually evolve fraud protection and implement features to support new telecom regulations",
			"Propose and implement performance optimizations",
		],
		minimumQualifications: [
			"BS/BA in Computer Science, Network Engineering or equivalent experience with telecommunications services.",
			"Strong background in developing and deploying VoIP systems (SIP)",
			"Experience in real-time software",
			"Programming experience in Python and/or Ruby, Javascript",
			"At least 3 years experience of service provider deployment and integration",
			"Ability to work independently with support from other teams",
			"Ability to mentor other engineers and teams working within your product",
			"Experience with open source SIP and network systems",
			"Ability to make an impact quickly",
			"Experience working with Asterisk",
			"Be a good human",
		],
		preferredQualifications: [
			"4+ years of Ruby on Rails experience",
			"Experience developing in Kamailio",
			"Ability to adapt to change and continuously improve",
		],
		youMightLikeThisJob:
			"<p>You are tired of paying so much for phone services. You are tired of not having a secure network. You want to help create one of the most secure VoIP networks out there, and make it affordable. In short, you want to solve problems that individuals and business owners care about by providing a good service at an affordable price. Your mission, should you choose to accept it, is not to impress stock holders and the fat cats out there, but to do good work and see it take off like a rocket ship. Is that something you want?</p>",
	},
	"senior-backend-developer": {
		title: "Senior Backend Developer",
		overview:
			"<p>Two Barrels is hiring a Senior Backend Developer specializing in the Domain Registrar space for $185,000/year. You will be a traditional company employee. This is a full time 40 hour/week position with company benefits. This is a remote position. Our main office is in Spokane, WA and we have satellite offices in Austin, TX and Salt Lake City, UT.</p><p>As a Senior Backend Developer, you will be given a brand-new project within the domain registration space, and will get the opportunity to do a lot of cool new things. This is a uniquely rare position to make a direct impact on the business and on our clients because you will help us build out this new offering. Let’s be honest, the domain registrar space can be done better, and if you want to be a part of making it better this is the right opportunity.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$185,000/year",
		responsibilities: [
			"Defining, designing, and implementing high-volume, scalable API systems which will interface with both internal and with external API’s provided by third parties",
			"Work closely with product team to make this a great solution for our clients",
			"Communicate consistently with stakeholders, managers, and other teams about releases",
			"Participate in training and development of others, as directed",
			"Be willing to learn, grow, and help all of us continually get better at what we do",
			"Be a good human",
		],
		minimumQualifications: [
			"Bachelor’s degree in computer science or other equivalent degree/experience",
			"Minimum 6 years full stack application development, software test automation experience, and object oriented development",
			"Professional experience developing in Ruby on Rails",
			"Programming experience in Python and/or Ruby, Javascript",
			"Experience building and documenting API’s",
			"Ability to design for security and scalability without compromise",
			"Professional history with JSON, XML and/or other serialized formats",
		],
		preferredQualifications: [
			"Understanding of internet name resolving protocols",
			"WAN programming experience",
		],
		youMightLikeThisJob:
			"<p>You are a competent engineer and have been stuck in a creativity box even though you have creative solutions bursting at the seams. You want to break out of that box, buck the system, and make something amazing.</p><p>Coding is your go to, but you also like being part of the planning and vision of the product. Oh yeah, you area also product-minded, it’s kind of a big deal around here, and ends up making a dang good product. You just want things to be better, and want to be a part of making things better.</p><p>While it’s a great job, it’s just a job. You value your time. Work is more fun when you know you have awesome things to look forward to. Kick butt during the day and enjoy your time at home.</p><p>You also might just be a domain nut like us.</p><p>#BI-Remote</p>",
	},
	"senior-data-engineer": {
		title: "Senior Data Engineer",
		overview:
			"<p data-renderer-start-pos='1'>Two Barrels is hiring a Senior Data Engineer for $150,000/year. You will be a traditional company employee. This is a full time 40 hour M-F remote position with company benefits.</p><p data-renderer-start-pos='181'>As a Senior Data Engineer at Two Barrels, you will work closely with our Software and Analyst teams to manage everything that has to do with data. This role will help get large datasets into the hands of people that need it while also making sure it doesn’t adversely impact other things we have going on in our software ecosystem. There will be a heavy focus on infrastructure, data pipelines and scalable database design – we want someone who can help us improve our current databases and infrastructure and maintain it in a cost-effective manner. This is more than just building and maintaining ETL pipelines. We need innovation, creativity, and solutions that will have a significant impact on how our data is handled and created.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$150,000/year",
		responsibilities: [
			"Focus on data infrastructure. Lead and build out data services/platforms from scratch (using OpenSource tech).",
			"Creating and maintaining transparent, bulletproof ETL (extract, transform, and load) pipelines that cleans, transforms, and aggregates unorganized and messy data into databases or data sources.",
			"Collaborate closely with our Data Analysts to get them the data they need.",
			"Identify, design, and implement internal process improvements: automating manual processes, optimizing data delivery, re-designing infrastructure for greater scalability, etc.",
			"Improve existing data models while implementing new business capabilities and integration points.",
			"Creating proactive monitoring so we learn about data breakages or inconsistencies right away.",
			"Maintaining internal documentation of how the data is housed and transformed.",
			"Improve existing data models, and design new ones to meet the needs of data consumers across Two Barrels.",
			"Stay current with latest cloud technologies, patterns, and methodologies; share knowledge by clearly articulating results and ideas to fellow engineers, data analysts, and stakeholders.",
		],
		minimumQualifications: [
			"Bachelor’s (BA or BS) in computer science, or related field.",
			"4+ years of experience working in a data engineer role, or related position.",
			"4+ years of experience with Postgres, specifically with RDS.",
			"4+ years of AWS experience, specifically S3, Glue, IAM, EC2, DDB, and other related data solutions.",
			"Experience working with Redshift, DBT, Snowflake, Apache Airflow, Azure Data Warehouse, or other industry standard big data or ETL related technologies.",
			"Experience working with both analytical and transactional databases. ",
			"Advanced working SQL (Preferably PostgreSQL) knowledge and experience working with relational databases.",
			"Experience with Grafana or other monitoring/charting systems.",
			"Proven knowledge of data platforms and tangible examples of designing and developing complex data pipelines to support better decision making in the business.",
			"Experience hosting and operating data platforms in cost efficient manner.",
			"Ability to translate business requirements into non-technical, lay terms.",
			"Proven expertise with data architecture design and deployment, data modeling, and database development.",
		],
		preferredQualifications: [],
		youMightLikeThisJob:
			"<ul><li>You are eager to ask questions and find out the 'why'.</li><li>You want to be a part of a team making some really cool software.</li><li>You are driven to creatively approach solutions based on clients needs.</li><li>You love open source technology and feel passionate about companies and developers who make decisions based on data.</li><li>You want your work to have a long-term, meaningful purpose.</li></ul><p><b>#BI-Remote</b></p>",
	},
	"security-engineer": {
		title: "Security Engineer",
		overview:
			"<p>Two Barrels is hiring a Security Engineer for $175,000/year. You will be a traditional company employee. This is a full time 40 hour/week position with company benefits. This is a remote position. Our main office is in Spokane WA, and we have satellite offices in Austin TX and Salt Lake City UT.</p><p>We are expanding our team to include a Security Engineer to be 100% focused on our security efforts. As the right candidate, you will have experience working in-house as a full-time penetration tester, a regular 3rd party bug bounty program pen tester, or in a similar security type role. Your job will be to identify our vulnerabilities to help keep our information safe and secure.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$175,000/year",
		responsibilities: [
			"Understand and safely use various open source penetration testing tools and when appropriate, emulating hacker tactics, techniques, procedures",
			"Create security vulnerability reports for both technical and executive audiences",
			"While in-between assessments, you will be expected to help our security engineers think through solutions to problems you find",
			"Automate tasks and script at a basic level to enhance penetration testing processes",
			"Passion for learning new technologies and processes, and contributing to refining existing capabilities",
			"Communicate with stakeholders (technical and non-technical), both verbal and written",
			"Stay up to date on 0 day exploits for tech stacks we use",
		],
		minimumQualifications: [
			"Solid fundamentals in webapp and network pentesting (2+ years). Pentesting experience in mobile apps, APIs, and/or cloud environments a bonus",
			"Experience with Linux, cloud environment testing as well as Ruby and Python web frameworks",
			"Understanding of security issues for desktop, virtual, cloud services and network infrastructures",
			"Working knowledge of information systems security standards/practices (e.g., access control and system hardening, system audit and log file monitoring, security policies, and incident handling)",
			"Experience with secure network protocols and encryption of communications between networked hosts",
			"Experience in IT systems and security policies, standards, industry trends, and techniques",
			"Experience with assessing APT threats, Penetration Testing, Vulnerability Management, attack methodologies, forensics analysis techniques, malware analysis, attack surface comprehension, Cyber Threat Emulation operations, Cyber Advanced Threat Emulation Team operations and research, identification, and/or verification of new APT TTPs",
			"Fundamental understanding of security knowledge of testing mobile, native applications, web applications, distributed and database systems",
			"Must be detail-oriented and possess strong problem-solving skills and ability to analyze for potential future issues",
			"Solid understanding of common webapp vulnerabilities, exploitation techniques, and remediation options",
		],
		preferredQualifications: [],
		youMightLikeThisJob:
			"<p>You’ve changed a price on a website you were checking out on to see if it worked. You’ve messed around where you shouldn’t have and you’ve always thought it would be fun to do that full time in a way that didn’t make you feel like an evil person or that karma would catch up to you. Maybe you’ve messed with folks in the past too much and want to earn some good karma points by helping us secure our high volume software and systems.</p><p><b>#BI-Remote</b></p>",
	},
	"senior-front-web-developer": {
		title: "Senior Front-End Web Developer",
		overview:
			"<p>Two Barrels is hiring a Senior Front-End Web Developer for $150,000/year. You will be a traditional company employee. This is a full time 40 hour/week position with company benefits. This is a remote position. Our main office is in Spokane WA, and we have satellite offices in Austin TX and Salt Lake City UT.</p><p>As a Senior Front-End Web Developer at Two Barrels, you’ll be given large-scale web projects and be asked to break these down into tasks for Junior Front-End Developers and Front-End Web Developers while maintaining focus on larger goals and projects. Our ideal candidate would be someone who has been successful in multiple front-end positions over the years and is looking to mentor a crew of talented, less-experienced developers and help take our websites to the next level. That will require you to be someone who doesn’t believe there’s only one right way to do things and your mindset is focused on growth, not the way things currently are.</p><p><strong>What’s in a title?</strong></p><p>Here at Two Barrels we don’t take titles very seriously. We know for recruiting purposes we need to call our jobs something, so we started with labeling and differentiating them in a fairly traditional way with “junior, mid, senior”. However, we’ve realized that was putting our employees in a box and wasn’t allowing us to uniquely identify their individual contributions, strengths and professional goals. Once you join our team the titles kinda get dropped as we expect everyone to work with everyone regardless of title or experience. We have taken the approach of evaluating candidates and employees on a “level” basis. It makes it a little easier internally to talk about growing into the next level without there being this huge chasm between what it means to be a Junior Engineer vs. a Mid Engineer. Our levels have expectations set for each one and it’s the responsibility of the manager and employee to make sure there is alignment. We do this through quarterly conversations where we discuss employee progression, if the work is challenging, and to ensure they feel fairly compensated for their work and expertise. Basically, levels gives us more flexibility to help people grow in their careers. But sure, you can post your title on LinkedIn as what makes sense to the rest of the world.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$150,000/year",
		responsibilities: [
			"Launch and Maintain Websites",
			"Take ownership of front-end components - from architecture to development, deployment and maintenance",
			"Optimize Sites for Scale and Feasibility",
			"Work with a team of writers and designers to crank out awesome websites",
			"Mentor junior and mid-level developers",
			"Ability to troubleshoot issues and provide valid solutions",
			"Accurately replicating mock ups into fully fledged websites through clean code and execution",
		],
		minimumQualifications: [
			"BS in CS, Design, Engineering or relevant work experience ",
			"At least 6 years of experience in a professional environment",
			"4-6 years of experience working with HTML and CSS",
			"4-6 years of working knowledge of CSS Frameworks, preferably Bootstrap",
			"4-5 years of working knowledge of CSS Preprocessors (SASS, LESS)",
			"6+ years of experience working with JavaScript and jQuery skills",
			"4-6 years of experience with PHP",
			"Expert with Responsive Web Design",
			"A solid understanding of how Content Management Systems work",
			"Experience developing custom Wordpress themes",
			"Experience using compilers and build tools ",
			"Experience with Task Runners (GULP, Webpack, Grunt)",
			"Experience using JavaScript Frameworks like Vue or React",
			"Interest in learning/researching new technologies and web development trends/practices ",
			"Understanding of SEO principles",
			"Strong analytical skills with excellent problem solving abilities",
			"Strong desire to build, deliver results, take ownership, and drive projects",
			"Experience mentoring junior/mid level developers and leading project groups",
			"Experience understanding, mapping, designing, developing, and testing systems",
		],
		preferredQualifications: ["Interest in Pokemon or curry"],
		youMightLikeThisJob:
			"<p>You’re someone with an easy-going disposition who can see the logical solution to a complex problem. You have no problem acknowledging when something isn’t working right and, inherently, you know how to fix it. You’re also able to recognize the noise for what it is: just noise. If that sounds like you and you’d like to share the things you’ve learned over the years with some of our less-experienced devs, while recognizing that you don’t always have to be the smartest person in the room, we’d love to have you be a part of our team and help make us better.</p><p><b>#BI-Remote</b></p>",
	},
	"devops-engineers": {
		title: "Senior DevOps Engineer",
		overview:
			"<p>Two Barrels is hiring a Sr. DevOps Engineer. You will be a traditional company employee. This is a full time 40 hour/week position with company benefits. This is a remote position. Our main office is in Spokane WA, and we have satellite offices in Austin TX and Salt Lake City UT.</p><p>You’ll work directly with other DevOps engineers on our teams, and alongside the rest of engineering to build, automate, and manage our infrastructures so they can focus on their applications! If you’re looking for an opportunity to work at a scale few ever get to, this could be the right place for you!</p><p>What’s in a title?<br>Here at Two Barrels we don’t take titles very seriously. We know for recruiting purposes we need to call our jobs something, so we started with labeling and differentiating them in a fairly traditional way with “junior, mid, senior”. However, we’ve realized that was putting our employees in a box and wasn’t allowing us to uniquely identify their individual contributions, strengths and professional goals. Once you join our team the titles kinda get dropped as we expect everyone to work with everyone regardless of title or experience. We have taken the approach of evaluating candidates and employees on a “level” basis. It makes it a little easier internally to talk about growing into the next level without there being this huge chasm between what it means to be a Junior Engineer vs. a Mid Engineer. Our levels have expectations set for each one and it’s the responsibility of the manager and employee to make sure there is alignment. We do this through quarterly conversations where we discuss employee progression, if the work is challenging, and to ensure they feel fairly compensated for their work and expertise. Basically, levels gives us more flexibility to help people grow in their careers. But sure, you can post your title on LinkedIn as what makes sense to the rest of the world.</p>",
		location: "Remote | Spokane - Austin - SLC",
		duration: "Full Time",
		wage: "$140,000-$170,000/year",
		responsibilities: [
			"Be an automation advocate: you're passionate about finding ways to help speed up development processes.",
			"Manage AWS IAM users and IAM permissions through terraform",
			"Maintain and improve the team’s workflow. Work with senior developers to propose ideas and establish priority",
			"Look for improvements to lower or minimize team’s cloud footprint to save or limit spending",
			"Maintain, improve, and add to Kubernetes architecture ",
		],
		minimumQualifications: [
			"You have 5+ years of professional software experience in DevOps or a related field",
			"Experience working with tools like Terraform / Ansible / CloudFormation",
			"Experience with Docker",
			"Experienced and comfortable working in Git",
			"Experience with scripting (preferably ruby)",
			"Good knowledge of Cloud based architecture design patterns",
			"Strong Troubleshooting abilities",
			"Attention to detail",
		],
		preferredQualifications: [
			"Experience with AWS - EC2, ECS, RDS, SNS, VPC, Route53, SecretsManager, S3, Lambda, Autoscaling",
			"Experience with Ruby & Javascript",
			"Experience with disaster recovery and cloud security",
			"Experience with relational SQL database, we use Postgres",
			"Experience with Kubernetes - EKS, GKE, AKS, Helm, Helm Charts",
			"Experience building and maintaining CI / CD pipelines, we use Drone",
			"Experience with visualizing metrics using cloud analytics tools, we use Grafana",
		],
		youMightLikeThisJob:
			"<p>You’ve been always looking for that job that gives you the freedom to build crazy tools from scratch. You’ve always wondered if there’s a place where profits and titles aren’t everyone’s motivation. Where people just want you to make great software tools. You like the idea of working for a locally-owned and operated company that competes in an extremely competitive space nationwide. You like that your work matters today and will affect millions of our business customers and employees.</p><p>You love to help people, but you want to take part in the planning without being required to deal with stakeholders and project managers all day. You want to make cool stuff and help other devs out and the company. You want your cool stuff to be really good. But most importantly, if you made a dish of noodles and butter for someone and asked them what they thought of it, if they said it was okay or good and didn’t give you feedback, you’d feel a little left out… you’d want a little more… because okay or good isn’t fulfilling to you.</p><p>But at the same time… it’s just a job. Yourself/Family/Friends/Personal Time is number 1. Work is number 2 or 3. Our goal is to use the incredible business we are excited to be a part of to support all of our personal time. We all want to live a full personal life. We’ll have more fun working together during the day if we know there’s a clear cutoff. This way, we can create a work environment where we can not only go home at the end of the day, but mentally shut off work and mentally go home also. We focus on creating a welcoming, supportive job environment that pays well and doesn’t stress you out, so when you call it a day, you go have fun personally.</p><p><b>#BI-Remote</b></p>",
	},
	"director-of-software-engineering": {
		title: "Director of Software Engineering",
		overview:
			"<p>Two Barrels in Spokane, Washington is hiring as many Directors of Software Engineering as we can find to lead our growing team of developers. You’ll be a leader of how we engineer stuff. From software to architecture. We’re not really hung up on titles here… so call yourself Director, or Head, or Conductor. We kinda like Conductor as your main role will be ensuring that our engineering team stays on the rails. Our “Director” level is a level here in development. You could say we’re still engineering it as we speak, but our main goal is that our directors of this or that have groups of engaged engineers and coders that they are technically leading, pushing, and mentoring to be better engineers and make better products here. We run about 50 products and you’ll be in charge of 15-30 engineers. Or less… Or more… It’s fluid and the driving force is doing good work and making employees happy.</p><p>You’re an excellent coder still, we’re talking hardcore tech skills with an affinity for open source. But you also really enjoy mentoring and supporting other engineers when it comes to technical leadership to tackle the most impactful projects across the organization. We don’t view our Director level as “managers”. We have Software Development Managers and Operations Managers that aren’t super technical based. Within our company, this is the career path coders take that would rather stay more technical than people manager.</p><p>This is a remote or work whatever you want position. We’d prefer you be around Spokane, Salt Lake, or Austin to have a hub base out of one of our three main technical offices, but we’re open to good talent anywhere in the US.</p>",
		location: "Spokane WA, Austin TX, Salt Lake UT vicinity preferred",
		duration: "Full Time",
		wage: "$200,000/year. We are family owned and run, so there's no share compensation or bonus structure as part of the compensation package.",
		responsibilities: [
			"All Engineering: Software, Database, Architecture, etc.",
			"Manage and scale our teams for future growth",
			"Develop solutions and applications for business services, while leading and mentoring the team",
			"Focus on team culture and personal development",
			"Ensure technical feasibility of software and API designs",
			"Drive product roadmap and execution, and participate in technical design",
			"Identify and correct issues that impact performance, reliability, and scalability",
		],
		minimumQualifications: [
			"You can show a lot of screwups you've had and how you've pivoted on large scale applications",
			"You can show how you've lead and managed large scale software and developer engineering teams",
			"7+ years' experience with software development and engineering (Ruby preferred but not required)",
			"5+ years’ experience managing and developing software development teams of 15-30 engineers and support",
			"Understanding of cloud (AWS) architectures and design patterns",
			"Experience working cross functionally in an Agile environment",
			"Experience developing mission critical applications and solutions",
			"Ability to design complete systems. Up to date on industry trends, best practices and change management",
			"10-15 years of front-end, back-end and REST API software design and implementation of commercial software products or 3-5 years of SaaS based product development",
		],
		preferredQualifications: [
			"You're a nice person",
			"You're amazing at communicating but also the true technical lead with all things engineering and development",
			"You have led a team of 30+ hardworking, passionate, smart people and helped them and the company they work for achieve!",
		],
		youMightLikeThisJob:
			"<p>We’re family owned and operated. It’s a high high impact role, and the company isn’t driven by building a product we hope will sell someday. We’re into open source and you should be also. We have a lot of good humans that work here, but we want to help them grow and fulfill their mental stimulation. We need help with that process and we as a company are going to accomplish amazing things along the way. You might consider yourself an Anti – Thought Leader…</p>",
	},
	"chief-marketing-officer": {
		title: "Chief Marketing Officer",
		overview:
			"<p>Two Barrels is hiring a Chief Marketing Officer.</p><p>We’re looking for a CMO with deep experience and understanding of all things digital marketing.</p><p>We find ourselves in a weird spot. We’ve grown about 780 percent over the last 3 years. A good marketing feat by itself, but extraordinary once you get into some of the details. Like… we actually don’t have a single employee with the word “marketing” in their job title…. so how in the crap did that happen? We don’t know… but it did. We have about 30-35 to maybe 50 people that you could say fall under the marketing umbrella. We have impressive folks and skillset groups like content writers, seos, ppc, affiliate managers, social media folks, videographers, full blown design team, UI/UX, front end developers, product owners, product managers, project managers, full blown revenue teams, and that’s just on the front end. We have a much larger team on the back end for the software. We have always done marketing without really thinking of it as marketing. We need to grow this group to be in the 150-200 employee range and want your help to do so. It’s all high impact, high volume, tough digital competition, and there’s no cap on where we could take it if we’re organized, have a plan, and execute.</p><p>We launch some big things and, although we know our goal when we begin, a week later, when other priorities come up, we might forget that we already have some heavy campaigns over here while we start something else. And well… our people accomplish amazing things, but sometimes it’s hard to remember that we’re all trying to track in one direction and stay with a consistent message.</p><p>So we’re looking for a been there done that CMO (with an e-commerce digital background) to help drive what we do. We’d like you to be extremely skilled at online marketing with the experience of having run larger campaigns and navigated companies with 800+ employees. We’d like you to eventually help come up with some of the vision, but that would be some time down the road after you truly get what we do and who we market to.</p><p>What does your job look like day 1? You’ll need to be comfortable pushing and leading PPC campaign spends over 40 million a year, Affiliate campaign spends over 20 million a year, SEO campaigns over 30 million a year, and direct client marketing spends over 30 million a year. You should be comfortable actually logging into a portal and adjusting an audience target, a CPA budget, or an impression share goal. What’s unique about this company is we’re a small business, kind of playing like a medium sized business. We’re scrappy. You should be also. There’s no real budget here or specific goals set by executives. The only goal for the job is to do good work, maximize your potential, and see where things go.</p>",
		location: "Spokane - Austin - Salt Lake City",
		duration: "Full Time",
		wage: "Up to $350,000 DOE. It's a family owned and operated business, and as such, it's just a normal type salary compensation package. Relocation assistance available for Spokane only. Depending on your network and ability to attract talent locally, we are also considering candidates who already live near our Austin TX or Salt Lake City UT offices, but we cannot offer relocation assistance to these cities.",
		responsibilities: [
			"Drive our marketing by telling a brand story.",
			"Lead a current team of roughly 30-50 employees and grow it to 200-250.",
			"Run a 40-80 million plus DIGITAL budget.",
			"Gain customer trust through our marketing that leads to conversions.",
			"Communicate with our different skillsets and ensure coordination among them.",
			"We're about 95% working remote at this point and will probably be largely remote for awhile. You should be comfortable managing onsite and from a video screen.",
			"Connect with our 3 million plus business customers.",
			"We manage our company under the product concept.... and agile concepts. You should be comfortable working in this realm.",
			"Compete with very well funded funny money blowing VC and PE companies that don't care about CPAs.",
		],
		minimumQualifications: [
			"In depth experience running social, ppc, affiliate, seo, and all things digital marketing. We're 100% digital.",
			"Experience working in high volume/low price point industries, not low volume/high price point.",
			"Experience working in high volume website oriented business sales organizations. Think 30,000+ orders a day. It's a fire hose.",
			"Experience running marketing budgets of our size ($40 million+).",
			"You're a little wily and you like leading wily folks.",
			"You're competitive.",
			"Show us the pain you've gone through on a failed campaign and how you pivoted to success.",
			"Experience telling brand stories to large markets to build trust.",
			"You've led a successful team of marketers and been a part of growing that team.",
			"You should have a background in e-commerce, all our services & products are only sold online.",
			"Have a deep understanding of dumping leads into a funnel and increasing our conversion rates and life time values, while keeping our cpas as low as possible.",
			"Have some hyfluffery bouncing around up there about your stance on activation within logical decision based marketing versus the importance of just focusing on brand marketing and what your plan here would be. It'll take awhile, but once you get your head around what on earth we're doing here, you'll have a chance to chart the path we're on and probably have a pretty large budget to play with by that time.",
			"The job is in Spokane, WA (unless you already live in Austin or SLC). If you don't live in Austin or SLC, you must be in Spokane or be willing to relocate eventually, like maybe after a year or so, and for a little bit, it will primarily be onsite while you figure out what on earth is going on here, go back home, and maybe 6 months from now consider relocating to Spokane, even though like 95%+ of your group is currently working remote and most will probably stay that way indefinitely.",
		],
		preferredQualifications: [
			"Experience working with renewal/subscription based services.",
			"Previous experience leading and managing a remote team.",
			"You've been a CMO before. Like an actual CMO type role... but a digital focused one",
		],
		youMightLikeThisJob:
			"<p>As we keep scaling, it feels like the right time to hire a CMO. Like an actual CMO. A couple years ago we wouldn’t have been ready, but we are today. What seems really unique about this position is you have a blank slate. You could make a marketing group how you’ve always thought it might be made. Yet, you already have a very skilled team and a 40 million a year + budget at your disposal. And you’re currently kicking everyone’s rear. Like, we pick up twice the market share of our first closest competitor. There are many states where you could add up every single one of our competitors market share and it still doesn’t add up to ours. So you get to join a winning team. And if someone picks a fight, we typically throw the budget out the window and just duke it out. We’re family owned and operated, so no investors, no debt. Just the game, and the game is fun.</p><p>But we also acknowledge the game is changing, and we need to change as well.</p><p>We now find ourselves fighting against companies that don’t have to make anything pencil because they’re backed by venture capital. While we kick their faces in with a fifth of the budget, all while being profitable, the companies are becoming monsters. They just keep getting bigger, more sophisticated, smarter, more numbers based, more focused, while being fueled by more and more funny money, so it’s time for us to be more intentional about what we do here.&nbsp; We like the fight, but we want to position ourselves in as good of a spot as we can to keep winning, or at least not get arrogant, and get crushed by the next round of VC backed funny money startups with a couple hundred million to blow. We like competing against talented companies, though. It forces us to keep growing and improve our game. And we need someone like you to help us grow into the future.</p>",
	},
	"junior-graphic-designer": {
		title: "Junior Graphic Designer",
		overview:
			"<p>Two Barrels is hiring a Junior Graphic Designer starting between $55,000 – $60,000 a year. This is a hybrid position, required to be located in Spokane, WA. The position is full-time, 40 hours, Monday-Friday.</p><p>We are looking for someone with a basic knowledge of UI, branding and identity, and illustration and who wants to further their experience and knowledge with the help of other creative minds. The ideal candidate will be a strong team player and play well with others.</p><p>The role works with a portfolio of many websites and an ever-expanding set of software tools, but they are all in-house projects (no external clients). Projects may include web designs/redesigns, app development, spot illustrations, iconography, logo/brand development, brand campaigns for social media and external channels, and graphic support on video and animation projects.</p><p>We’re looking for a Jr. Graphic Designer who will draw on their skills and experience to complete each job correctly and on time. In addition, we need a team member who enjoys researching our client base and thinking outside the box to raise the quality of the projects you’ll work on. This is a great opportunity to dig in and do amazing things.</p>",
		location: "Spokane, WA",
		duration: "Full Time",
		wage: "$55,000-$60,000/year (Candidates qualify for the higher end of the range if you have a degree in Design.)",
		responsibilities: [
			"The Junior Graphic Designer is a crucial part of our marketing creative team and is expected to design web & mobile UI, spot graphics, logos, presentations and more. ",
		],
		minimumQualifications: [
			"1-3 years experience in a graphic design position",
			"Provide a portfolio with your most creative designs",
			"Combination of proficiency in Adobe programs: Photoshop, Illustrator, XD, InDesign, Acrobat, Premiere and After Effects",
			"Experience running marketing budgets of our size ($40 million+).",
			"Exposure to Figma, Sketch, Procreate and Canva",
			"Ability to produce quality work on aggressive timelines",
			"Ability to have an open mind with stakeholder requests",
			"Willingness to work through group discussions, critique and find solutions to problems with epic design. You find this process fun, and part of creating an epic final product. ",
		],
		preferredQualifications: [
			"Bachelors or Associates degree in Design and/or relevant work experience ",
			"HTML/CSS knowledge and experience",
			"Custom brand creation like logos and graphics",
			"Vector and rasterized image creation (please be able to accurately explain the difference between the two, if asked)",
			"Experience in and comfort with an Agile work environment",
			"Great communication skills (written and verbal)",
			"Ability to multi-task ",
			"The opposite of a boring personality, nothing too opposite though",
			"Experience creating appealing infographics",
		],
		youMightLikeThisJob:
			"<p>You love to design cool stuff</p><p>You want your cool stuff to become even cooler by learning from other creative minds</p><p>Learn new design tools/gadgets</p><p>You don’t want to go work at a start-up where you might lose your job any day</p><p>You’d like to move to more of a culture and process of research first, design second</p><p>• It interests you to take the time to dig into whom we’re targeting, making things, adjusting after seeing how they perform, and designing not just to finish a project but to make an impact and change. This job might be a rare opportunity to have the freedom to do this.</p>",
	},
};

export const benefits = [
	{
		text: "Great Wage",
		route: "/jobs/benefits/wages",
	},
	{
		text: "WFH comfort package",
		route: "/jobs/benefits/wfh-comfort-package",
	},
	{
		text: "22 days paid time off (29 days after 3 years. Flexible time off after 5 years!)",
		route: "/jobs/benefits/pto",
	},
	{
		text: "4% retirement matching through Fidelity",
		route: "/jobs/benefits/retirement",
	},
	{
		text: "100% employer-paid medical, dental and vision for employees",
		route: "/jobs/benefits/health-insurance",
	},
	{
		text: "Maternity and Paternity Leave",
		route: "/jobs/benefits/maternity-paternity-leave",
	},
	{
		text: "Flexible hours",
		route: "/jobs/benefits/flexible-hours",
	},
	{
		text: "Coffee shop next door",
		route: "/jobs/benefits/coffee",
	},
	{
		text: "<del>Crappy parking?</del> Oh, I mean a cool downtown location for easy public transportation options…",
		route: null,
	},
];
